### ISSUE TITLE
rocket-broker启动后容器关闭Exist 253

### ISSUE THREAD

**Issue by yun-yun** [foxiswho/docker-rocketmq#12]
我使用环境变量
`JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms512M -Xmx512M -Xmn128m"` 时，broker无法启动，控制台打印：
```
broker      | ======================================
broker      | -server -Xms3971M -Xmx3971M -Xmn800M -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=3971M -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre/lib/ext:/home/rocketmq/rocketmq-4.5.2/bin/../lib -cp .:/home/rocketmq/rocketmq-4.5.2/bin/../conf:
```
然后我把环境变量改为：
`JAVA_OPTS: "-Duser.home=/opt -server -Xms512M -Xmx512M -Xmn128m"`
后启动成功。控制台还是打印
```
broker      | ======================================
broker      | -server -Xms3971M -Xmx3971M -Xmn800M -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=3971M -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.222.b10-0.el7_6.x86_64/jre/lib/ext:/home/rocketmq/rocketmq-4.5.2/bin/../lib -cp .:/home/rocketmq/rocketmq-4.5.2/bin/../conf:
```
这是什么原因，有什么影响吗？我看到Xmx还是4个G

**Comment by foxiswho** [comment]
你是从哪边使用的  docker?  docker-compose ?   。
-server -Xms994M -Xmx994M -Xmn200M -XX:+UseG1GC -XX:G1HeapRegionSize=16m -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -XX:SoftRefLRUPolicyMSPerMB=0 -XX:SurvivorRatio=8 -verbose:gc -Xloggc:/dev/shm/mq_gc_%p.log -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintAdaptiveSizePolicy -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=30m -XX:-OmitStackTraceInFastThrow -XX:+AlwaysPreTouch -XX:MaxDirectMemorySize=994M -XX:-UseLargePages -XX:-UseBiasedLocking -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/ext:/home/rocketmq/rocketmq-4.6.1/bin/../lib -Duser.home=/opt -Xms512M -Xmx512M -Xmn128m -cp .:/home/rocketmq/rocketmq-4.6.1/bin/../conf:
The broker[broker-a, 172.18.0.3:10911] boot success. serializeType=JSON and name server is rmqnamesrv:9876


这是我拿本地  测试，可以打印出 自定义设置的

**Comment by foxiswho** [comment]
你重新拉取一下最新的 ，  估计 是 4.5.2版 的 docker-compose.yaml  文件 有个bug  没修改

**Comment by yun-yun** [comment]
我的docker-compose是这样写的
```
version: '3'
services:
   mq-namesrv:
        image: foxiswho/rocketmq:server-4.5.2
        container_name: mq-namesrv
        ports:
            - 9876:9876
        volumes:
            - "$PWD/logs/rocketmq/logs/namesrv:/opt/logs"
            - "$PWD/data/rocketmq/store/namesrv:/opt/store"
        environment:
            JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    mq-broker:
        image: foxiswho/rocketmq:broker-4.5.2
        container_name: mq-broker
        ports:
            - 10909:10909
            - 10911:10911
        volumes:
            - "$PWD/logs/rocketmq/logs/broker:/opt/logs"
            - "$PWD/data/rocketmq/store/broker:/opt/store"
            - "$PWD/config/rocketmq/broker.conf:/etc/rocketmq/broker.conf"
        environment:
            JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms512M -Xmx512M -Xmn128m"
        command: ["/bin/bash","mqbroker","-c","/etc/rocketmq/broker.conf","-n","mq-namesrv:9876"]
        depends_on:
            - mq-namesrv
    mq-ng:
        image: styletang/rocketmq-console-ng
        container_name: mq-ng
        ports:
            - 8180:8080
        environment:
            JAVA_OPT_EXT: "-Drocketmq.namesrv.addr=mq-namesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
        depends_on:
            - mq-namesrv
```
使用了
```
JAVA_OPT_EXT: "-Duser.home=/opt -server -Xms512M -Xmx512M -Xmn128m"
```
后，还是打印
Xms3971M -Xmx3971M -Xmn800M
我是从master拉的代码
