### ISSUE TITLE
broker exited with code 253

### ISSUE THREAD

**Issue by yuxiaojie** [foxiswho/docker-rocketmq#14]
按 rmq/docker-compose.yml 下的配置去开启 broker 一直启动不起来，`exited with code 253`，然后把 docker-compose.yml 中配置的 
```
JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
``` 
改为 
```
JAVA_OPTS: " -Duser.home=/opt" 
JAVA_OPT_EXT: "-server -Xms512M -Xmx512M -Xmn128m"
``` 
就能正常启动了

不能启动的完整 docker-compose.yml 
```yaml
version: '3.5'
services:
  rmqnamesrv:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    environment:
        TZ: Asia/Shanghai
        JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn128m"
    volumes:
      - /tmp/rocketmq/logs/nameserver:/home/rocketmq/logs
    command: sh mqnamesrv
    networks:
        rmq:
          aliases:
            - rmqnamesrv

  rmqbroker-a:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-a
    ports:
      - 10911:10911
      # - 10909:10909
    volumes:
      - /tmp/rocketmq/logs/broker-a:/home/rocketmq/logs
      - /tmp/rocketmq/store/broker-a:/home/rocketmq/store
      - /tmp/broker-a.conf:/etc/rocketmq/broker.conf
    environment:
        TZ: Asia/Shanghai
        JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker-a
          
networks:
  rmq:
    name: rmq
    driver: bridge
```

环境信息
```shell
# 镜像版本
foxiswho/rocketmq:4.7.0

# 操作系统
Darwin Jmac.local 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`

# docker 版本
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
