### ISSUE TITLE
无法启动broker，也没有日志

### ISSUE THREAD

**Issue by YAGAMIL** [foxiswho/docker-rocketmq#25]
我直接用你的docker-compose.yaml按照你的说明直接启动部署是正常的，但我要配置日志路径和我自己的conf映射时，配置完之后，日志也没有，broker也启动不起来，我去看你的docker构建指令，logs，store确实都在home目录下，而且你默认的conf也没有改动这些，但是用你默认的sh部署却都在opt目录下，然后我也没改opt，只改了我宿主机的目录路径，然后就凉了，我人都傻了，搞不懂
这是我基于你的yaml改动的结果
version: '3.5'

```
services:
  rmqnamesrv-a:
    image: foxiswho/rocketmq:4.7.0
    #    image: registry.cn-hangzhou.aliyuncs.com/foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - /home/matcloud/DATA/rocketmq/nameserver-a/logs:/opt/logs
      - /home/matcloud/DATA/rocketmq/nameserver-a/store:/opt/store
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqnamesrv"]
    networks:
      rmq:
        aliases:
          - rmqnamesrv-a
  rmqbroker:
    image: foxiswho/rocketmq:4.7.0
    #    image: registry.cn-hangzhou.aliyuncs.com/foxiswho/rocketmq:4.7.0
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - /home/matcloud/DATA/rocketmq/broker-b/logs:/opt/logs
      - /home/matcloud/DATA/rocketmq/broker-b/store:/opt/store
      - /home/matcloud/DATA/rocketmq/broker-b/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    command: ["sh","mqbroker","-c","/etc/rocketmq/broker.conf","-n","rmqnamesrv:9876","autoCreateTopicEnable=true"]
    depends_on:
      - rmqnamesrv-a
    networks:
      rmq:
        aliases:
          - rmqbroker

  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8765:8080
    environment:
      JAVA_OPTS: "-Drocketmq.namesrv.addr=rmqnamesrv:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqconsole

networks:
  rmq:
    name: rmq
    driver: bridge
```
当我用你的默认配置不改动直接执行sh脚本的时候，opt/log目录下时会有日志文件产生的，但是我只改掉宿主机映射路径的时候，我进入容器的opt/log下可以找到路径，单却没有任何日志文件产生，真的把我整懵了

IDEA部署完的路径映射
![image](https://user-images.githubusercontent.com/16757285/103860852-5baada80-50f7-11eb-9151-b8b8ca0bfe46.png)

**Comment by YAGAMIL** [comment]
当我自己编写了配置执行的时候，我发现你的log和store根本就不在opt下，而是在“
/home/rocketmq/logs/rocketmqlogs”和“/home/rocketmq/store”这两个容器路径下，只有使用你的git直接克隆并./start.sh执行的话，opt下才会有东西，但是好像也会才上述两个路径下有一份，忘记了，这是我集群部署的yml

```
version: '3.5'
services:
  rmqnamesrv-a:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
#      - /home/matcloud/DATA/rocketmq/logs/nameserver-a:/opt/logs
      - /home/matcloud/DATA/rocketmq/store/nameserver-a:/opt/store
    command: sh mqnamesrv
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    networks:
      rmq:
        aliases:
          - rmqnamesrv-a

  rmqnamesrv-b:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqnamesrv-b
    ports:
      - 9877:9876
    volumes:
#      - /home/matcloud/DATA/rocketmq/logs/nameserver-b:/opt/logs
      - /home/matcloud/DATA/rocketmq/store/nameserver-b:/opt/store
    command: sh mqnamesrv
    environment:
      JAVA_OPT_EXT: "-Duser.home=/opt -Xms512M -Xmx512M -Xmn128m"
    networks:
      rmq:
        aliases:
          - rmqnamesrv-b

  rmqbroker-a:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-a
    ports:
      - 10909:10909
    volumes:
#      - /home/matcloud/DATA/rocketmq/broker-a/logs:/opt/logs
#      - /home/matcloud/DATA/rocketmq/broker-a/store:/opt/store
      - /home/matcloud/DATA/rocketmq/broker-a/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
    command: sh mqbroker -c /etc/rocketmq/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-a

  rmqbroker-b:
    image: foxiswho/rocketmq:4.7.0
    container_name: rmqbroker-b
    ports:

      - 10911:10911
    volumes:
#      - /home/matcloud/DATA/rocketmq/broker-b/logs:/opt/logs
#      - /home/matcloud/DATA/rocketmq/broker-b/store:/opt/store
      - /home/matcloud/DATA/rocketmq/broker-b/conf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-b:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx256m -Xmn256m"
#    command: sh mqbroker -c /etc/rocketmq/broker.conf autoCreateTopicEnable=true &
    command: sh mqbroker -c /etc/rocketmq/broker.conf autoCreateTopicEnable=true &
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    networks:
      rmq:
        aliases:
          - rmqbroker-b
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8765:8080
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      rmq:
        aliases:
          - rmqconsole
networks:
  rmq:
    name: rmq
    driver: bridge
```
我把原本映射的opt去掉了排除是我自己的问题，直接去容器的opt路径下看，结果opt下什么都没有生成
![image](https://user-images.githubusercontent.com/16757285/103866426-bc8ae080-5100-11eb-9046-f54fdeb5d0ec.png)
而日志和store都在容器的/home/rocketmq目录下
![image](https://user-images.githubusercontent.com/16757285/103866482-d6c4be80-5100-11eb-8358-13bb5e4d6364.png)
所以我不能用opt/logs映射，但是你的yml又是用的opt映射的，并且都是一样的镜像，所以我懵了
