### ISSUE TITLE
没有看到日志。

### ISSUE THREAD

**Issue by yhuihu** [foxiswho/docker-rocketmq#8]

**Comment by foxiswho** [comment]
容器内 目录
/opt/logs
/opt/store


外部目录，都需要你自己去配置映射的

**Comment by yhuihu** [comment]
> 容器内 目录
> /opt/logs
> /opt/store
> 
> 外部目录，都需要你自己去配置映射的

我进入foxiswho/rocketmq:broker和server容器里的logs和store里面都是空的

**Comment by yhuihu** [comment]
我进入broker容器内部，找到~/下的logs和/store是有数据的，并没有在/opt下
```
   environment:
        NAMESRV_ADDR: "rmqnamesrv:9876"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
```
